server:
  port: 8088
spring:
  application:
    name: study-shop-scheduler

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/study-shop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: myHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


elasticJob:

  serverlists: 127.0.0.1:2181  # 连接Zookeeper服务器的列表包括IP地址和端口号多个地址用逗号分隔如: host1:2181,host2:2181
  namespace: elastic-job  # Zookeeper的命名空间

  orderSimpleJob:
    jobName: orderSimpleJob #作业名称
    cron: 0/3 * * * * ？   # cron表达式，用于控制作业触发时间
    shardingTotalCount: 3  # 	作业分片总数
    shardingItemParameters: 0=beijing,1=shanghai,2=guangzhuou #分片序列号和参数用等号分隔，多个键值对用逗号分隔分片序列号从0开始，不可大于或等于作业分片总数如：0=a,1=b,2=c

  orderDataflowJob:
    jobName: orderDataflowJob #作业名称
    cron: 0/5 * * * * ？   # cron表达式，用于控制作业触发时间
    shardingTotalCount: 3  # 	作业分片总数
    shardingItemParameters: 0=beijing,1=shanghai,2=guangzhuou